-- Removes everything generated by seed_perf_test.sql, in FK-safe order.
-- Run phase by phase via the Supabase MCP execute_sql tool, same as the
-- generator. Does not touch the real catalogue (card_printings,
-- sellable_skus) -- that data predates this script and isn't tagged by it.
--
-- Safe to run even if real inventory/reservation activity has happened
-- since seeding: inventory_balances cleanup only removes rows that have
-- no remaining movement and no remaining reservation once the tagged rows
-- are gone, rather than assuming the table is untouched.

-- ============================================================
-- Step 1: Reservations backing perf_seed carts (no cascading FK
-- from carts, so these must go before the carts/customers do).
-- ============================================================
delete from inventory_reservations r
using carts c, auth.users u
where r.cart_id = c.id
  and c.customer_id = u.id
  and u.email like 'perftest+%@perftest.invalid';

-- ============================================================
-- Step 2: Tagged inventory movements.
-- ============================================================
delete from inventory_movements where reason = 'perf_seed';

-- ============================================================
-- Step 3: Balances left with nothing backing them (no movement,
-- no active reservation) after steps 1-2.
-- ============================================================
delete from inventory_balances b
where not exists (select 1 from inventory_movements m where m.fulfilment_node_id = b.fulfilment_node_id and m.sellable_sku_id = b.sellable_sku_id)
  and not exists (select 1 from inventory_reservations r where r.fulfilment_node_id = b.fulfilment_node_id and r.sellable_sku_id = b.sellable_sku_id and r.status = 'active');

-- ============================================================
-- Step 4: Tagged customers -- cascades to their orders (and
-- order_lines via orders' own cascade) and carts (and cart_lines
-- via carts' own cascade).
-- ============================================================
delete from auth.users where email like 'perftest+%@perftest.invalid';

-- ============================================================
-- Step 5: Tagged addresses (orders referencing them are already
-- gone via step 4's cascade, so no FK conflict).
-- ============================================================
delete from addresses where email like 'perftest-addr+%@perftest.invalid';

-- ============================================================
-- Verify: all zero.
-- ============================================================
select
  (select count(*) from auth.users where email like 'perftest+%@perftest.invalid') as remaining_customers,
  (select count(*) from addresses where email like 'perftest-addr+%@perftest.invalid') as remaining_addresses,
  (select count(*) from orders where order_number like 'PERF-%') as remaining_orders,
  (select count(*) from inventory_movements where reason = 'perf_seed') as remaining_movements;
