-- No-op reconciliation: this migration's original intent (route
-- publish_suggested_price()/set_price_override()/clear_price_override() through
-- emit_integration_event() instead of a broken raw integration_events insert) was
-- already achieved by 20260724140000_audit_events.sql, which redefined all three
-- functions with the correct integration_events (organisation_id, aggregate_id,
-- aggregate_type, event_type, payload) columns and added record_audit_event()
-- calls. This migration originally reverted set_price_override()/clear_price_override()
-- back to unprefixed parameter names (published_price_id, fulfilment_node_id),
-- which both fails outright against the p_-prefixed signature audit_events.sql
-- creates (CREATE OR REPLACE FUNCTION cannot rename parameters) and would have
-- reintroduced the ambiguous-column-reference bug audit_events.sql's prefixing
-- fixed in the first place.
--
-- Recorded as a no-op so migration history matches what's actually deployed;
-- see 20260724220000_fix_pricing_review_permissions.sql for the same pattern
-- applied to the pricing-review functions.
do $$ begin end $$;
